server:
  port: 8080
spring:
  mail:
    host: smtp.qq.com
    # 你的QQ邮箱，这里为发件人，填自己的即可
    username: 1449029481@qq.com
    # 你的QQ邮箱授权码
    password: xybeouiummjkhfjb
  application:
    #应用的名称，可
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/regice?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\img\